{{- if .Values.gatewayAPI.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "quickhaul.fullname" . }}-gateway
  labels:
    {{- include "quickhaul.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gatewayAPI.className | default "kong" }}
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
{{- end }}
