{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quickhaul.fullname" . }}-ingress
  labels:
    {{- include "quickhaul.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-frontend
                port:
                  number: 80
          - path: /api/locations
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-location-service
                port:
                  number: 8001
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-auth-service
                port:
                  number: 8002
          - path: /api/bookings
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-booking-service
                port:
                  number: 8003
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-notification-service
                port:
                  number: 8004
          - path: /api/otp
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-otp-service
                port:
                  number: 8005
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: {{ include "quickhaul.fullname" . }}-payment-service
                port:
                  number: 8006
{{- end }}
