apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quickhaul-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quickhaul-allow-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector: {}
  policyTypes:
  - Ingress
