{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickhaul-redis
  labels:
    {{- include "quickhaul.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: quickhaul-redis
  template:
    metadata:
      labels:
        app: quickhaul-redis
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port | default 6379 }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
