sonar.projectKey=Resolveops-AI_resolveops-application
sonar.organization=resolveops-ai
sonar.projectName=ResolveOps Application
sonar.projectVersion=1.0

sonar.sources=frontend,services,quickhaul
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/coverage/**,**/*.min.js,**/helm/**,**/kubernetes/**,**/docs/**

sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml,services/api-gateway-service/coverage.xml,services/notification-service/coverage.xml,services/auth-service/coverage.xml
