namespaceOverride: quickhaul-prod
replicaCount: 2
global:
  imageRegistry: "" # injected via ArgoCD helm.parameters — do not hardcode here
frontend:
  image:
    tag: v2.0.0
  replicaCount: 2
locationService:
  image:
    tag: v2.0.0
  replicaCount: 2
authService:
  image:
    tag: v2.0.0
  replicaCount: 2
bookingService:
  image:
    tag: v2.0.0
  replicaCount: 2
notificationService:
  image:
    tag: v2.0.0
  replicaCount: 2
otpService:
  image:
    tag: v2.0.0
  replicaCount: 2
paymentService:
  image:
    tag: v1.0.0
  replicaCount: 2
config:
  mongoUri: mongodb://quickhaul-mongodb:27017
  redisUrl: redis://quickhaul-redis:6379/0
  frontendUrl: https://quickhaul.sathvikdevops.site
mongodb:
  auth:
    username: quickhaul
    password: change-me-prod
    database: quickhaul_prod
  persistence:
    enabled: true
    size: 8Gi
redis:
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
ingress:
  enabled: true
  className: azure/application-gateway
  host: quickhaul.sathvikdevops.site
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 700m
    memory: 768Mi
gatewayAPI:
  enabled: false
  host: ''
