namespaceOverride: quickhaul-dev
replicaCount: 1
global:
  imageRegistry: "" # injected via ArgoCD helm.parameter
frontend:
  image:
    tag: "dev-d6d413b"
  replicaCount: 1
  service:
    type: LoadBalancer
locationService:
  image:
    tag: "dev-d6d413b"
  replicaCount: 1
authService:
  image:
    tag: "dev-d6d413b"
  replicaCount: 1
bookingService:
  image:
    tag: "dev-d6d413b"
  replicaCount: 1
notificationService:
  image:
    tag: "dev-d6d413b"
  replicaCount: 1
otpService:
  image:
    tag: "dev-d6d413b"
  replicaCount: 1
paymentService:
  image:
    tag: "dev-3b9d276"
  replicaCount: 1
config:
  mongoUri: mongodb://quickhaul-mongodb:27017
  redisUrl: redis://quickhaul-redis:6379/0
  frontendUrl: https://quickhaul.sathvikdevops.site
mongodb:
  auth:
    username: quickhaul
    password: change-me-dev
    database: quickhaul_dev
  persistence:
    enabled: true
    size: 2Gi
redis:
  persistence:
    enabled: false
ingress:
  enabled: true
  className: azure-application-gateway
  host: quickhaul.sathvikdevops.site
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399,404"
  tls:
    - hosts:
        - quickhaul.sathvikdevops.site
      secretName: quickhaul-tls
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi
gatewayAPI:
  enabled: false
  host: ''
