apiVersion: v1
kind: ConfigMap
metadata:
  name: resolveops-config
data:
  APP_ENV: "dev"
  LOG_LEVEL: "info"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  GITHUB_INTELLIGENCE_SERVICE_URL: "http://github-intelligence-service:8000"
  AZURE_INTELLIGENCE_SERVICE_URL: "http://azure-intelligence-service:8000"
  AWS_INTELLIGENCE_SERVICE_URL: "http://aws-intelligence-service:8000"
  AI_RCA_SERVICE_URL: "http://ai-rca-service:8000"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8000"
  NEXT_PUBLIC_API_BASE_URL: "/api"
  STORAGE_ACCOUNT_NAME: ""
  BLOB_CONTAINER_NAME: "artifacts"
  SERVICE_BUS_FQDN: "resolveops-sb-05.servicebus.windows.net"
  SERVICE_BUS_QUEUE_NAME: "notification-requested"
  DEBUG_LOG_OTP: "false"
