apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- serviceaccount.yaml
- secretproviderclass.yaml
- ingress.yaml
- frontend.yaml
- api-gateway-service.yaml
- auth-service.yaml
- azure-intelligence-service.yaml
- ai-rca-service.yaml
- github-intelligence-service.yaml
- aws-intelligence-service.yaml
- notification-service.yaml
- hpa.yaml
- networkpolicy.yaml
- pdb.yaml


images:
- name: notification-service
  newName: notification-service
  newTag: v1.0.1
- name: resolveopsacr05.azurecr.io/ai-rca-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/api-gateway-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/auth-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/aws-intelligence-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/azure-intelligence-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/github-intelligence-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/notification-service
  newTag: v1.0.0
- name: resolveopsacr05.azurecr.io/resolveops-frontend
  newTag: v1.0.0
