apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity
spec:
  provider: azure
  secretObjects:
  - secretName: resolveops-app-secrets
    type: Opaque
    data:
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: smtp-user
      key: SMTP_USER
    - objectName: smtp-password
      key: SMTP_PASSWORD
    - objectName: ai-provider-api-key
      key: AI_PROVIDER_API_KEY
    - objectName: github-webhook-secret
      key: GITHUB_WEBHOOK_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "ab0e6d5f-bff8-4046-acb3-250739f98ae8"
    keyvaultName: "sathvik-kv-08"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: smtp-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: smtp-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: resolveops-ai-key
          objectAlias: ai-provider-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: github-webhook-secret
          objectType: secret
          objectVersion: ""
    tenantId: "81c422d3-b9ef-49b9-b8a9-b10a5f4ce484"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity-db
spec:
  provider: azure
  secretObjects:
  - secretName: resolveops-secrets
    type: Opaque
    data:
    - objectName: database-url
      key: DATABASE_URL
    - objectName: jwt-secret
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "ab0e6d5f-bff8-4046-acb3-250739f98ae8"
    keyvaultName: "sathvik-kv-08"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-url
          objectType: secret
          objectVersion: ""
    tenantId: "81c422d3-b9ef-49b9-b8a9-b10a5f4ce484"
    
