apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Resolveops-AI/resolveops-application.git
    targetRevision: main
    path: quickhaul/helm/quickhaul
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
